eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: film-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/films/**
        - id: screening-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/screenings/**
        - id: hall-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/halls/**
        - id: auth-service
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/auth/**
        - id: auth-service
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/users/**

security:
  jwt:
    token:
      secret:
        access: levc/guxCQY5xgOePnfbG52ZjB4Jn+PvZMK+DBxwBKHG3ODmlQQ8FBWO4juJkTJd1htUl82Io+LAz54kKbKmQw==

management:
  tracing:
    sampling:
      probability: 1.0