eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8050

spring:
  application:
    name: hall-service

  liquibase:
    change-log: classpath:db/changelog/db-changelog-hall-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5002/hall_db
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0