eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port:
    8060

spring:
  application:
    name: screening-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinema-management-db
    username: cinema-management-username
    password: cinema-management-password

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

application:
  config:
    films-url: http://localhost:8070/api/v1/films
    halls-url: http://localhost:8050/api/v1/halls
    user-url: http://localhost:8010/api/v1/user
    tickets-url: http://localhost:8040/api/v1/tickets

management:
  tracing:
    sampling:
      probability: 1.0