eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8040

spring:
  application:
    name: tickets-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinema-management-db
    username: cinema-management-username
    password: cinema-management-password

application:
  config:
    screening-url: http://localhost:8060/api/v1/screenings

management:
  tracing:
    sampling:
      probability: 1.0